<?php

namespace Database\Seeders;

use App\Enums\EmploymentStatus;
use App\Enums\Gender;
use App\Enums\MaritalStatus;
use App\Enums\ParticipantCategory;
use App\Models\Examination;
use App\Models\ExaminationAdult;
use App\Models\ExaminationPregnantMother;
use App\Models\ExaminationTeen;
use App\Models\ExaminationToddler;
use App\Models\Participant;
use App\Models\ParticipantAdult;
use App\Models\ParticipantTeen;
use App\Models\ParticipantToddler;
use App\Models\Pregnancy;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ParticipantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        ExaminationAdult::truncate();
        ExaminationTeen::truncate();
        ExaminationPregnantMother::truncate();
        ExaminationToddler::truncate();
        Examination::truncate();
        ParticipantAdult::truncate();
        ParticipantTeen::truncate();
        ParticipantToddler::truncate();
        Pregnancy::truncate();
        Participant::truncate();
        Schema::enableForeignKeyConstraints();

        $participants = [
            // =========================================================================
            // 1. IBU HAMIL (10 Peserta - Kategori: pregnant_mother)
            // =========================================================================
            [
                'nik' => '3318084503980001',
                'name' => 'Dewi Ratnasari',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '1998-03-05',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '03',
                'phone' => '081234567801',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364511',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Budi Prasetyo',
                    'pregnancy_number' => 2,
                    'birth_spacing_years' => 3,
                    'weight_before_pregnancy' => 52.00,
                    'height' => 156.00,
                    'last_menstrual_period' => '2026-03-10',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318085208010002',
                'name' => 'Siti Rahmawati',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '2001-08-12',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '02',
                'phone' => '085712345602',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364512',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Agus Nugroho',
                    'pregnancy_number' => 1,
                    'birth_spacing_years' => null,
                    'weight_before_pregnancy' => 48.50,
                    'height' => 153.00,
                    'last_menstrual_period' => '2026-04-15',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318086011950003',
                'name' => 'Rina Marlina',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '1995-11-20',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '01',
                'phone' => '082134567803',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364513',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Dedi Irawan',
                    'pregnancy_number' => 3,
                    'birth_spacing_years' => 4,
                    'weight_before_pregnancy' => 55.00,
                    'height' => 158.00,
                    'last_menstrual_period' => '2026-01-20',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318084105030004',
                'name' => 'Fitri Handayani',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '2003-05-01',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '04',
                'phone' => '087812345604',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Tri Santoso',
                    'pregnancy_number' => 1,
                    'birth_spacing_years' => null,
                    'weight_before_pregnancy' => 43.00,
                    'height' => 152.00,
                    'last_menstrual_period' => '2026-05-02',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318085407970005',
                'name' => 'Dian Permatasari',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '1997-07-14',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '03',
                'phone' => '081398765405',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364515',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Bambang Supriyanto',
                    'pregnancy_number' => 2,
                    'birth_spacing_years' => 2,
                    'weight_before_pregnancy' => 54.00,
                    'height' => 160.00,
                    'last_menstrual_period' => '2026-02-14',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318086512990006',
                'name' => 'Anisa Rahayu',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '1999-12-25',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '02',
                'phone' => '085612345606',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364516',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Eko Sulistyo',
                    'pregnancy_number' => 1,
                    'birth_spacing_years' => null,
                    'weight_before_pregnancy' => 50.00,
                    'height' => 155.00,
                    'last_menstrual_period' => '2026-06-01',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318085404960007',
                'name' => 'Mega Utami',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '1996-04-14',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '01',
                'phone' => '082212345607',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364517',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Ahmad Riyadi',
                    'pregnancy_number' => 2,
                    'birth_spacing_years' => 5,
                    'weight_before_pregnancy' => 56.00,
                    'height' => 159.00,
                    'last_menstrual_period' => '2026-03-01',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318084309020008',
                'name' => 'Putri Wulandari',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '2002-09-03',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '04',
                'phone' => '081298765408',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Fajar Sidik',
                    'pregnancy_number' => 1,
                    'birth_spacing_years' => null,
                    'weight_before_pregnancy' => 49.00,
                    'height' => 154.00,
                    'last_menstrual_period' => '2026-01-10',
                    'status' => 'active',
                ],
            ],
            // 2 Ibu Hamil Belum Pernah Periksa (Riwayat Kosong)
            [
                'nik' => '3318085901940009',
                'name' => 'Nurul Hidayah',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '1994-01-19',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '03',
                'phone' => '087712345609',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364519',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Hendra Setiawan',
                    'pregnancy_number' => 2,
                    'birth_spacing_years' => 4,
                    'weight_before_pregnancy' => 53.00,
                    'height' => 157.00,
                    'last_menstrual_period' => '2026-07-01',
                    'status' => 'active',
                ],
            ],
            [
                'nik' => '3318084206000010',
                'name' => 'Eka Novitasari',
                'category' => ParticipantCategory::PregnantMother,
                'birth_date' => '2000-06-02',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '02',
                'phone' => '081312345610',
                'has_bpjs' => true,
                'bpjs_number' => '0001827364520',
                'is_active' => true,
                'pregnancy' => [
                    'husband_name' => 'Rian Hidayat',
                    'pregnancy_number' => 1,
                    'birth_spacing_years' => null,
                    'weight_before_pregnancy' => 47.00,
                    'height' => 151.00,
                    'last_menstrual_period' => '2026-06-20',
                    'status' => 'active',
                ],
            ],

            // =========================================================================
            // 2. BALITA (6 Peserta - Kategori: toddler)
            // =========================================================================
            [
                'nik' => '3318081204240011',
                'name' => 'Aditya Pratama',
                'category' => ParticipantCategory::Toddler,
                'birth_date' => '2024-04-12',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '03',
                'phone' => '081234567801',
                'has_bpjs' => true,
                'bpjs_number' => '0002827364521',
                'is_active' => true,
                'toddler' => [
                    'parent_name' => 'Budi Prasetyo',
                ],
            ],
            [
                'nik' => '3318085508240012',
                'name' => 'Bilqis Humaira',
                'category' => ParticipantCategory::Toddler,
                'birth_date' => '2024-08-15',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '02',
                'phone' => '085712345602',
                'has_bpjs' => true,
                'bpjs_number' => '0002827364522',
                'is_active' => true,
                'toddler' => [
                    'parent_name' => 'Agus Nugroho',
                ],
            ],
            [
                'nik' => '3318082001250013',
                'name' => 'Danendra Alvaro',
                'category' => ParticipantCategory::Toddler,
                'birth_date' => '2025-01-20',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '01',
                'phone' => '082134567803',
                'has_bpjs' => true,
                'bpjs_number' => '0002827364523',
                'is_active' => true,
                'toddler' => [
                    'parent_name' => 'Dedi Irawan',
                ],
            ],
            [
                'nik' => '3318086205250014',
                'name' => 'Gibran Alfarizi',
                'category' => ParticipantCategory::Toddler,
                'birth_date' => '2025-05-22',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '04',
                'phone' => '087812345604',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'toddler' => [
                    'parent_name' => 'Tri Santoso',
                ],
            ],
            [
                'nik' => '3318081510250015',
                'name' => 'Kenzo Rafandra',
                'category' => ParticipantCategory::Toddler,
                'birth_date' => '2025-10-15',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '03',
                'phone' => '081398765405',
                'has_bpjs' => true,
                'bpjs_number' => '0002827364525',
                'is_active' => true,
                'toddler' => [
                    'parent_name' => 'Bambang Supriyanto',
                ],
            ],
            // 1 Balita Belum Pernah Periksa
            [
                'nik' => '3318084502260016',
                'name' => 'Zahra Salsabila',
                'category' => ParticipantCategory::Toddler,
                'birth_date' => '2026-02-05',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '02',
                'phone' => '085612345606',
                'has_bpjs' => true,
                'bpjs_number' => '0002827364526',
                'is_active' => true,
                'toddler' => [
                    'parent_name' => 'Eko Sulistyo',
                ],
            ],

            // =========================================================================
            // 3. ANAK REMAJA (12 Peserta - Kategori: teenager)
            // =========================================================================
            [
                'nik' => '3318085203110017',
                'name' => 'Nadia Putri Azzahra',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2011-03-12',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '01',
                'phone' => '082212345617',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364531',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Ahmad Riyadi',
                ],
            ],
            [
                'nik' => '3318081501100018',
                'name' => 'Rizky Dwi Prasetyo',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2010-01-15',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '03',
                'phone' => '081234567818',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364532',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Sutrisno',
                ],
            ],
            [
                'nik' => '3318081008090019',
                'name' => 'Bagas Saputra',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2009-08-10',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '02',
                'phone' => '085712345619',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364533',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Kuswanto',
                ],
            ],
            [
                'nik' => '3318086512100020',
                'name' => 'Amanda Cantika',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2010-12-25',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '04',
                'phone' => '087812345620',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Joko Widodo',
                ],
            ],
            [
                'nik' => '3318080506080021',
                'name' => 'Dimas Arya Wijaya',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2008-06-05',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '03',
                'phone' => '081398765421',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364535',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Supriyadi',
                ],
            ],
            [
                'nik' => '3318084709090022',
                'name' => 'Tiara Maharani',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2009-09-17',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '02',
                'phone' => '085612345622',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364536',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Sunaryo',
                ],
            ],
            [
                'nik' => '3318081811080023',
                'name' => 'Farhan Maulana',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2008-11-18',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '01',
                'phone' => '082134567823',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364537',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Sukirman',
                ],
            ],
            [
                'nik' => '3318085604100024',
                'name' => 'Zaskia Nur Aini',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2010-04-16',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '04',
                'phone' => '081298765424',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364538',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Slamet Raharjo',
                ],
            ],
            [
                'nik' => '3318082307090025',
                'name' => 'Bayu Tri Atmojo',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2009-07-23',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '03',
                'phone' => '087712345625',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Sugiyono',
                ],
            ],
            [
                'nik' => '3318084910110026',
                'name' => 'Salsa Bella Putri',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2011-10-09',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '02',
                'phone' => '081312345626',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364540',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Mulyono',
                ],
            ],
            // 2 Remaja Belum Pernah Periksa
            [
                'nik' => '3318081402080027',
                'name' => 'Galang Daniswara',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2008-02-14',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '01',
                'phone' => '082212345627',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364541',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Haryanto',
                ],
            ],
            [
                'nik' => '3318086806100028',
                'name' => 'Nabila Syahrani',
                'category' => ParticipantCategory::Teenager,
                'birth_date' => '2010-06-28',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '04',
                'phone' => '085712345628',
                'has_bpjs' => true,
                'bpjs_number' => '0003827364542',
                'is_active' => true,
                'teen' => [
                    'parent_name' => 'Hartono',
                ],
            ],

            // =========================================================================
            // 4. USIA PRODUKTIF (15 Peserta - Kategori: productive)
            // =========================================================================
            [
                'nik' => '3318081005880029',
                'name' => 'Rudi Hermawan',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1988-05-10',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '03',
                'phone' => '081234567829',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364545',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::PrivateEmployee,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318080308830030',
                'name' => 'Agus Setiawan',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1983-08-03',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '02',
                'phone' => '085712345630',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364546',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318081809820031',
                'name' => 'Wahyu Hidayat',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1982-09-18',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '01',
                'phone' => '082134567831',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364547',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Entrepreneur,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318085007870032',
                'name' => 'Endang Tri Astuti',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1987-07-20',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '04',
                'phone' => '087812345632',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364548',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318082504890033',
                'name' => 'Hendra Gunawan',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1989-04-25',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '03',
                'phone' => '081398765433',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364549',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::CivilServant,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318084508900034',
                'name' => 'Sri Wahyuni',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1990-08-15',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '02',
                'phone' => '085612345634',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364550',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318081406840035',
                'name' => 'Ahmad Fauzi',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1984-06-14',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '01',
                'phone' => '082212345635',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318085501860036',
                'name' => 'Suryani Indah',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1986-01-25',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '04',
                'phone' => '081298765436',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364552',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Entrepreneur,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318081203850037',
                'name' => 'Bambang Pamungkas',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1985-03-12',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '03',
                'phone' => '087712345637',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364553',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::PrivateEmployee,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318084911920038',
                'name' => 'Retno Kusuma',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1992-11-09',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '02',
                'phone' => '081312345638',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364554',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318080803930039',
                'name' => 'Joko Susilo',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1993-03-08',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '01',
                'phone' => '085812345639',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364555',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Entrepreneur,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318086212910040',
                'name' => 'Lestari Anggraini',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1991-12-22',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '04',
                'phone' => '081223344540',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364556',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Other,
                    'employment_other' => 'Pedagang Pasar',
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            // 3 Usia Produktif Belum Pernah Periksa
            [
                'nik' => '3318082210810041',
                'name' => 'Tri Wibowo',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1981-10-22',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '03',
                'phone' => '087799887741',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318086409890042',
                'name' => 'Maya Rosita',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1989-09-24',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '02',
                'phone' => '081388776642',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364558',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318081604940043',
                'name' => 'Eko Prasetyo',
                'category' => ParticipantCategory::Productive,
                'birth_date' => '1994-04-16',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '01',
                'phone' => '085777889943',
                'has_bpjs' => true,
                'bpjs_number' => '0004827364559',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::PrivateEmployee,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Single,
                ],
            ],

            // =========================================================================
            // 5. USIA LANSIA (10 Peserta - Kategori: adult)
            // =========================================================================
            [
                'nik' => '3318080101570044',
                'name' => 'Sukirno',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1957-01-01',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '01',
                'phone' => '085812345644',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364561',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Widowed,
                ],
            ],
            [
                'nik' => '3318086104610045',
                'name' => 'Kartini',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1961-04-21',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '03',
                'phone' => '081223344545',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364562',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318081207540046',
                'name' => 'Sunardi',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1954-07-12',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '02',
                'phone' => '087712345646',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364563',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Widowed,
                ],
            ],
            [
                'nik' => '3318081809630047',
                'name' => 'Sutikno',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1963-09-18',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '04',
                'phone' => '081299887747',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364564',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Entrepreneur,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318080505510048',
                'name' => 'Darmo',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1951-05-05',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '03',
                'phone' => '085611223348',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Widowed,
                ],
            ],
            [
                'nik' => '3318085811580049',
                'name' => 'Sumarni',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1958-11-18',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '04',
                'rw' => '02',
                'phone' => '081234567849',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364566',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Widowed,
                ],
            ],
            [
                'nik' => '3318082403550050',
                'name' => 'Parto Suwito',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1955-03-24',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '01',
                'phone' => '085712345650',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364567',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318086208620051',
                'name' => 'Suparmi',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1962-08-22',
                'gender' => Gender::Female,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '03',
                'rw' => '04',
                'phone' => '082134567851',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364568',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Housewife,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            // 2 Lansia Belum Pernah Periksa
            [
                'nik' => '3318081606590052',
                'name' => 'Kastono',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1959-06-16',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '01',
                'rw' => '03',
                'phone' => '087812345652',
                'has_bpjs' => false,
                'bpjs_number' => null,
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Entrepreneur,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Married,
                ],
            ],
            [
                'nik' => '3318080709480053',
                'name' => 'Wagiman',
                'category' => ParticipantCategory::Adult,
                'birth_date' => '1948-09-07',
                'gender' => Gender::Male,
                'address' => 'Ds. Tondomulyo, Kec. Jakenan, Kab. Pati',
                'rt' => '02',
                'rw' => '02',
                'phone' => '081398765453',
                'has_bpjs' => true,
                'bpjs_number' => '0005827364570',
                'is_active' => true,
                'adult' => [
                    'employment' => EmploymentStatus::Farmer,
                    'employment_other' => null,
                    'marital_status' => MaritalStatus::Widowed,
                ],
            ],
        ];

        foreach ($participants as $data) {
            $toddlerData = $data['toddler'] ?? null;
            $pregnancyData = $data['pregnancy'] ?? null;
            $teenData = $data['teen'] ?? null;
            $adultData = $data['adult'] ?? null;

            unset($data['toddler'], $data['pregnancy'], $data['teen'], $data['adult']);

            $existing = Participant::where('nik_hash', hash('sha256', $data['nik']))->first();

            if ($existing) {
                $existing->update($data);
                $participant = $existing;
            } else {
                $participant = Participant::create($data);
            }

            if ($toddlerData) {
                $participant->toddler()->updateOrCreate([], $toddlerData);
            }

            if ($pregnancyData) {
                $participant->pregnancies()->updateOrCreate(
                    [
                        'participant_id' => $participant->id,
                        'husband_name' => $pregnancyData['husband_name'],
                    ],
                    $pregnancyData
                );
            }

            if ($teenData) {
                $participant->teen()->updateOrCreate([], $teenData);
            }

            if ($adultData) {
                $participant->adult()->updateOrCreate([], $adultData);
            }
        }
    }
}
